controller_list:
  - name: Arm
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: gripper
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - gripper_base_joint
      - gripper_finger1_inner_knuckle_joint
      - gripper_finger1_finger_tip_joint
      - gripper_finger1_joint
      - gripper_finger1_finger_joint
      - gripper_finger2_inner_knuckle_joint
      - gripper_finger2_finger_tip_joint
      - gripper_finger2_joint
      - gripper_finger2_finger_joint
      
